# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 08:15
from __future__ import unicode_literals

import account.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='refer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
