# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
