# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180616_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
